application: geodatastore
version: 1
runtime: python
api_version: 1

handlers:
- url: /gen
  script: geoserv.py
- url: /gen/.*
  script: geoserv.py
- url: /genOLD/.*
  script: geoservOLD.py
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: html.py
